import fs from 'node:fs';
const code = fs.readFileSync('plugin.js', 'utf8');
console.log('Length:', code.length);
console.log('Has _drawingsCollectionRef:', code.includes('_drawingsCollectionRef'));
console.log('Has lastRemoteApplyMs:', code.includes('lastRemoteApplyMs'));
console.log('Has degenerate element filter (v0.5.6 rename):', code.includes("isDegenerateElement"));
console.log('Has freedraw filter (legacy name, should be false):', code.includes("isDegenerateFreedraw"));
console.log('Has _cloneElementSnapshot helper (v0.5.6):', code.includes('function _cloneElementSnapshot'));
const cloneCallCount = (code.match(/_cloneElementSnapshot\(/g) || []).length;
console.log('Clone helper call sites (should be >= 4):', cloneCallCount);
console.log('Has sceneOrder in broadcast (v0.5.6 bug 7):', code.includes('sceneOrder: currentElements.map'));
console.log('Has sceneOrder in receive (v0.5.6 bug 7):', code.includes('Array.isArray(data.sceneOrder)'));
console.log('Has lb.clear() after remote:', code.includes('lb.clear()'));
const rafPattern = /requestAnimationFrame\(\(\) => requestAnimationFrame\(\(\) => \{\s*session\.applyingRemoteUpdate/;
console.log('No more double-rAF flag reset:', !rafPattern.test(code));
console.log('Has _installContextMenuGuard (v0.5.7):', code.includes('_installContextMenuGuard'));
const guardCallCount = (code.match(/_installContextMenuGuard\(/g) || []).length;
console.log('Guard helper call sites (should be 2 = 1 def + 1 call):', guardCallCount);
console.log('Context menu guard teardown:', code.includes('session._contextMenuGuardDispose'));
console.log('EXCAL_VERSION:', code.match(/const EXCAL_VERSION = '([^']+)'/)?.[1]);
